version: '3'

services:
  postgres:
    image: postgres:10.3
    environment:
      - POSTGRES_DB=opendatacube
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=opendatacube

  jupyter:
    build:
      context: .
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=opendatacube
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=opendatacube
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/notebooks
    shm_size: 1g
    command: jupyter notebook --ip="*" --NotebookApp.token='secretpassword'
