version: '3'

services:
  postgres:
    image: postgres:10.3
    environment:
      - POSTGRES_DB=opendatacube
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=opendatacube

  jupyterhub:
    build:
      context: .
    volumes:
      - ./jupyterhub_config.py:/etc/jupyterhub/jupyterhub_config.py
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=opendatacube
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=opendatacube
    ports:
      - "8000:8000"
    command: "jupyterhub --ip=\"*\" -f /etc/jupyterhub/jupyterhub_config.py"
